.pragma library

// GENERATED by scripts/assets/gen_settings.py from
// wisp/settings_schema.py. Do not edit; change the schema and
// regenerate. lib/settings.js builds on this table.

// every key the daemon validates, in schema order
var KEYS = ["budget.daily_usd", "budget.monthly_usd", "budget.gate_primary", "pointer.mode", "pointer.backend", "cua.dry_run", "cua.kill_switch", "cua.confirm", "cua.max_clicks_per_min", "cua.max_per_turn", "cua.timeout_ms", "audio.seconds", "agent.screenshots", "ui.theme", "brain.router", "brain.allow_paid", "keys.submap", "agents.act_max_steps", "agents.act_max_errors", "agents.act_max_parse_misses", "agents.writer_queue_max", "stt.provider"]

// keys the Panel edits: kind usd, int, bool or choice
var FIELDS = [
  {"key": "budget.daily_usd", "group": "budget", "kind": "usd", "label": "ui.set.daily", "widget": "number"},
  {"key": "budget.monthly_usd", "group": "budget", "kind": "usd", "label": "ui.set.monthly", "widget": "number"},
  {"key": "pointer.mode", "group": "pointer", "kind": "choice", "label": "ui.set.pointer", "widget": "choice", "options": ["guide", "drive", "auto"]},
  {"key": "cua.dry_run", "group": "cua", "kind": "bool", "label": "ui.set.dry_run", "widget": "toggle"},
  {"key": "cua.kill_switch", "group": "cua", "kind": "bool", "label": "ui.set.kill", "widget": "toggle"},
  {"key": "cua.confirm", "group": "cua", "kind": "choice", "label": "ui.set.confirm", "widget": "choice", "options": ["tier", "always"]},
  {"key": "cua.max_clicks_per_min", "group": "cua", "kind": "int", "label": "ui.set.clicks", "widget": "number", "min": 1, "max": 600},
  {"key": "cua.max_per_turn", "group": "cua", "kind": "int", "label": "ui.set.per_turn", "widget": "number", "min": 1, "max": 200}
]

// characters a config value may not contain (as a regex source)
var BAD_CHARS = "[\"\\\\#\\n]"
var USD_MAX = 100000

function field(key) {
  for (var i = 0; i < FIELDS.length; i++)
    if (FIELDS[i].key === key) return FIELDS[i]
  return null
}

function trim(s) { return String(s === undefined || s === null ? "" : s).replace(/^\s+|\s+$/g, "") }

// "" when the value may be written, else a copy key for the inline error.
// Same rules as wisp/settings_schema.problem(); a key the Panel does not
// edit is "ui.err.unknown".
function validate(key, raw) {
  var f = field(key)
  if (f === null) return "ui.err.unknown"
  var v = trim(raw)
  if (new RegExp(BAD_CHARS).test(v)) return "ui.err.chars"
  if (f.kind === "usd") {
    if (v === "") return ""
    if (!/^\d+(\.\d+)?$/.test(v)) return "ui.err.number"
    return Number(v) > USD_MAX ? "ui.err.range" : ""
  }
  if (f.kind === "int") {
    if (!/^\d+$/.test(v)) return "ui.err.number"
    var n = Number(v)
    return n < f.min || n > f.max ? "ui.err.range" : ""
  }
  if (f.kind === "bool") return v === "true" || v === "false" ? "" : "ui.err.choice"
  if (f.kind === "choice") return f.options.indexOf(v) >= 0 ? "" : "ui.err.choice"
  return "ui.err.unknown"
}
