#!/usr/bin/env python3
"""Compile the owned icon set into shell-plugin/lib/icons.js (plan KTD4).

Sources are hand-authored SVGs: assets/icons/src/*.svg (24 UI icons, 7 bar
glyphs, ghost cursor, beacon) plus assets/brand/mark.svg. Each is checked
against DESIGN-v2 5.6 (16px viewBox, one path, currentColor, 1.5px stroke,
square caps and mitred joins; fills and round caps only on the mark
family), optimized with svgo when it is on PATH, and written as path data
plus stroke metadata.

    python scripts/assets/build_icons.py              # write icons.js
    python scripts/assets/build_icons.py --sheet DIR  # review contact sheets
"""
import json
import pathlib
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "assets" / "icons" / "src"
MARK = ROOT / "assets" / "brand" / "mark.svg"
OUT = ROOT / "shell-plugin" / "lib" / "icons.js"
SVG_NS = "{http://www.w3.org/2000/svg}"

# Names allowed to fill: the mark, its filled bar states, the ghost cursor
# and the beacon. Round caps/joins: the mark family only (mark, bar-*).
FILLED = {"mark", "ghost-cursor", "beacon", "bar-listening", "bar-thinking",
          "bar-acting", "bar-needs-you", "bar-error"}


class IconError(ValueError):
    pass


def sources() -> list:
    return sorted(SRC.glob("*.svg")) + [MARK]


def _name(path: pathlib.Path) -> str:
    return path.stem


def validate(path: pathlib.Path) -> dict:
    """Check one source SVG; return {d, fill, stroke, width, cap, join,
    dash}. Raises IconError naming the file."""
    path = pathlib.Path(path)
    name = _name(path)

    def bad(msg):
        raise IconError(f"{path.name}: {msg}")

    try:
        root = ET.parse(path).getroot()
    except ET.ParseError as e:
        bad(f"not valid XML ({e})")
    if root.get("viewBox") != "0 0 16 16":
        bad(f"viewBox must be '0 0 16 16', got {root.get('viewBox')!r}")
    elems = list(root.iter())[1:]
    if len(elems) != 1 or elems[0].tag != SVG_NS + "path":
        bad("must contain exactly one <path> and nothing else")
    p = elems[0]
    if re.search(r"#[0-9a-fA-F]{3,8}\b", path.read_text()):
        bad("hex color literal; use currentColor")
    fill = p.get("fill", "black")
    stroke = p.get("stroke", "none")
    if fill not in ("none", "currentColor"):
        bad(f"fill must be none or currentColor, got {fill!r}")
    if stroke not in ("none", "currentColor"):
        bad(f"stroke must be none or currentColor, got {stroke!r}")
    filled, stroked = fill == "currentColor", stroke == "currentColor"
    if filled and name not in FILLED:
        bad("only the mark family, ghost cursor and beacon may fill")
    if not (filled or stroked):
        bad("draws nothing (no fill and no stroke)")
    meta = {"fill": filled, "stroke": stroked, "width": 0, "cap": "",
            "join": "", "dash": []}
    if stroked:
        mark_family = name == "mark" or name.startswith("bar-")
        meta["width"] = float(p.get("stroke-width", "1"))
        meta["cap"] = p.get("stroke-linecap", "butt")
        meta["join"] = p.get("stroke-linejoin", "miter")
        if meta["width"] != 1.5:
            bad("stroke-width must be 1.5")
        want = ("round", "round") if mark_family else ("square", "miter")
        if (meta["cap"], meta["join"]) != want:
            bad(f"caps/joins must be {want[0]}/{want[1]}")
        if p.get("stroke-dasharray"):
            meta["dash"] = [float(x) for x in
                            re.split(r"[\s,]+", p.get("stroke-dasharray"))]
    d = (p.get("d") or "").strip()
    if not d:
        bad("empty path data")
    meta["d"] = d
    return meta


def _optimize(path: pathlib.Path, d: str) -> str:
    """svgo-optimized path data (same geometry, compact syntax)."""
    if not shutil.which("svgo"):
        return re.sub(r"\s+", " ", d)
    out = subprocess.run(
        ["svgo", "--input", "-", "--output", "-"], input=path.read_text(),
        capture_output=True, text=True, check=True).stdout
    m = re.search(r'\sd="([^"]+)"', out)
    if not m:
        raise IconError(f"{path.name}: svgo output has no path data")
    return m.group(1)


def build() -> dict:
    icons = {}
    for path in sources():
        meta = validate(path)
        meta["d"] = _optimize(path, meta["d"])
        icons[_name(path)] = meta
    return icons


def render() -> str:
    icons = build()
    return "\n".join([
        ".pragma library",
        "",
        "// GENERATED by scripts/assets/build_icons.py from assets/icons/src",
        "// and assets/brand/mark.svg. Do not edit; change the SVG sources.",
        "// 16px grid; d is SVG path data for PathSvg. fill/stroke say how to",
        "// paint it in the icon color; width, cap, join, dash describe the",
        "// stroke (dash in px).",
        "",
        "var ICONS = " + json.dumps(icons, sort_keys=True,
                                    separators=(",", ":")),
        "",
        "function get(name) { return ICONS.hasOwnProperty(name) ? "
        "ICONS[name] : null }",
        "",
    ])


# --- review contact sheet --------------------------------------------------

BAR_STATES = [("bar-idle", "idle"), ("bar-listening", "listening"),
              ("bar-thinking", "deciding"), ("bar-acting", "acting"),
              ("bar-needs-you", "awaiting_choice"), ("bar-error", "error"),
              ("bar-offline", "offline")]


def _glyph(meta, x, y, size, color):
    s = size / 16
    attrs = []
    if meta["fill"]:
        attrs.append(f'fill="{color}"')
    else:
        attrs.append('fill="none"')
    if meta["stroke"]:
        attrs.append(f'stroke="{color}" stroke-width="{meta["width"]}" '
                     f'stroke-linecap="{meta["cap"]}" '
                     f'stroke-linejoin="{meta["join"]}"')
        if meta["dash"]:
            attrs.append('stroke-dasharray="%s"'
                         % " ".join(f"{v:g}" for v in meta["dash"]))
    return (f'<path transform="translate({x} {y}) scale({s:g})" '
            f'{" ".join(attrs)} d="{meta["d"]}"/>')


def sheet_svg(icons, theme_name, res) -> str:
    sys.path.insert(0, str(ROOT))
    from wisp import copy as wcopy
    t = res["tokens"]
    tone = {"muted": t["inkMuted"], "ember": t["ember"],
            "needsYou": t["needsYou"], "fail": t["fail"], "ok": t["ok"]}
    font = 'font-family="JetBrainsMono Nerd Font, DejaVu Sans Mono" font-size="10"'
    parts, y = [], 12
    parts.append(f'<text x="12" y="{y + 8}" fill="{t["ink"]}" {font}>'
                 f'{theme_name} ({res["mode"]}) bar 26px, glyph 16px</text>')
    y += 18
    # the bar strip at real size: 26px tall, 16px glyphs, status words
    parts.append(f'<rect x="0" y="{y}" width="100%" height="26" '
                 f'fill="{t["canvas"]}" stroke="{t["keyline"]}"/>')
    x = 12
    for name, status in BAR_STATES:
        color = tone[wcopy.status_tone(status)]
        parts.append(_glyph(icons[name], x, y + 5, 16, color))
        word = wcopy.status_word(status)
        parts.append(f'<text x="{x + 20}" y="{y + 17}" fill="{t["inkMuted"]}"'
                     f' {font}>{word}</text>')
        x += 28 + 7 * len(word)
    y += 40
    # bar glyphs + mark family at 16 / 24 / 48
    fam = [n for n, _ in BAR_STATES] + ["mark", "ghost-cursor", "beacon"]
    for size in (16, 24, 48):
        x = 12
        for name in fam:
            color = t["ember"] if icons[name]["fill"] or name == "mark" \
                else t["ink"]
            st = dict(BAR_STATES).get(name)
            if st:
                color = tone[wcopy.status_tone(st)]
            parts.append(_glyph(icons[name], x, y, size, color))
            x += max(size, 16) + 14
        y += size + 14
    # UI icons at 16 / 24 / 48 in ink, with labels at 16
    ui = sorted(n for n in icons if n not in fam)
    for size in (16, 24, 48):
        x = 12
        for name in ui:
            parts.append(_glyph(icons[name], x, y, size, t["ink"]))
            x += max(size, 16) + 14
        y += size + 14
    width = max(12 + len(ui) * 62, 900)
    body = "\n".join(parts)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
            f'height="{y}"><rect width="100%" height="100%" '
            f'fill="{t["canvas"]}"/>\n{body}\n</svg>\n')


def sheets(out_dir: pathlib.Path, themes: list) -> list:
    sys.path.insert(0, str(ROOT))
    from wisp import theme
    icons = build()
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in themes:
        res = theme.load(ROOT / "tests" / "fixtures" / "themes" / name)
        svg = out_dir / f"sheet-{name}.svg"
        svg.write_text(sheet_svg(icons, name, res))
        for zoom in (1, 2):
            png = out_dir / f"sheet-{name}@{zoom}x.png"
            subprocess.run(["resvg", "--zoom", str(zoom), str(svg), str(png)],
                           check=True)
            written.append(png)
    return written


def main(argv) -> int:
    if "--sheet" in argv:
        i = argv.index("--sheet")
        out = pathlib.Path(argv[i + 1])
        themes = argv[i + 2:] or ["vantablack", "catppuccin-latte"]
        for p in sheets(out, themes):
            print(p)
        return 0
    try:
        text = render()
    except IconError as e:
        print(f"icon build failed: {e}", file=sys.stderr)
        return 1
    OUT.write_text(text)
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
