#!/usr/bin/env python3
"""Generate shell-plugin/lib/settings_schema.js from wisp/settings_schema.py.

    python scripts/assets/gen_settings.py          # write the file
    python scripts/assets/gen_settings.py --check  # exit 1 if it is stale

The Panel settings tab and `wispd config` both read the schema, so the
generated table and validators cannot drift from the daemon's check.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from wisp import settings_schema as S  # noqa: E402

OUT = ROOT / "shell-plugin" / "lib" / "settings_schema.js"

_FUNCTIONS = r"""
function field(key) {
  for (var i = 0; i < FIELDS.length; i++)
    if (FIELDS[i].key === key) return FIELDS[i]
  return null
}

function trim(s) { return String(s === undefined || s === null ? "" : s).replace(/^\s+|\s+$/g, "") }

// "" when the value may be written, else a copy key for the inline error.
// Same rules as wisp/settings_schema.problem(); a key the Panel does not
// edit is "ui.err.unknown".
function validate(key, raw) {
  var f = field(key)
  if (f === null) return "ui.err.unknown"
  var v = trim(raw)
  if (new RegExp(BAD_CHARS).test(v)) return "ui.err.chars"
  if (f.kind === "usd") {
    if (v === "") return ""
    if (!/^\d+(\.\d+)?$/.test(v)) return "ui.err.number"
    return Number(v) > USD_MAX ? "ui.err.range" : ""
  }
  if (f.kind === "int") {
    if (!/^\d+$/.test(v)) return "ui.err.number"
    var n = Number(v)
    return n < f.min || n > f.max ? "ui.err.range" : ""
  }
  if (f.kind === "bool") return v === "true" || v === "false" ? "" : "ui.err.choice"
  if (f.kind === "choice") return f.options.indexOf(v) >= 0 ? "" : "ui.err.choice"
  return "ui.err.unknown"
}
"""


def render() -> str:
    def js(v):
        return json.dumps(v, ensure_ascii=True)
    fields = [f.panel_dict() for f in S.panel_fields()]
    rows = ",\n".join("  " + js(r) for r in fields)
    return "\n".join([
        ".pragma library",
        "",
        "// GENERATED by scripts/assets/gen_settings.py from",
        "// wisp/settings_schema.py. Do not edit; change the schema and",
        "// regenerate. lib/settings.js builds on this table.",
        "",
        "// every key the daemon validates, in schema order",
        f"var KEYS = {js(list(S.KEYS))}",
        "",
        "// keys the Panel edits: kind usd, int, bool or choice",
        f"var FIELDS = [\n{rows}\n]",
        "",
        "// characters a config value may not contain (as a regex source)",
        f"var BAD_CHARS = {js('[' + chr(34) + chr(92) * 2 + '#' + chr(92) + 'n]')}",
        f"var USD_MAX = {S.USD_MAX}",
    ]) + "\n" + _FUNCTIONS


def _name() -> str:
    try:
        return str(OUT.relative_to(ROOT))
    except ValueError:
        return str(OUT)


def main(argv) -> int:
    text = render()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{_name()} is stale; run "
                  "python scripts/assets/gen_settings.py")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
