#!/usr/bin/env python3
"""Generate shell-plugin/lib/copy.js from wisp/copy.py (plan KTD7).

    python scripts/assets/gen_copy.py          # write copy.js
    python scripts/assets/gen_copy.py --check  # exit 1 if copy.js is stale
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from wisp import copy as wcopy  # noqa: E402

OUT = ROOT / "shell-plugin" / "lib" / "copy.js"

_FUNCTIONS = r"""
function errorMessage(code) { return (ERRORS[code] || ERRORS[UNKNOWN_ERROR])[0] }

function errorHint(code) { return (ERRORS[code] || ERRORS[UNKNOWN_ERROR])[1] }

// UI string by key; an unknown key returns the key so a typo is visible.
function string(key) { return STRINGS.hasOwnProperty(key) ? STRINGS[key] : key }

function undash(s) { return String(s).replace(/\s*[—–]\s*/g, ": ").replace(/^\s+|\s+$/g, "") }

function statusWord(status) { return (STATUS[status] || STATUS[UNKNOWN_STATUS])[0] }

function statusTone(status) { return (STATUS[status] || STATUS[UNKNOWN_STATUS])[1] }

// Live-state word for every surface (pill, console status line, bar
// tooltip). Mirrors copy.word_view: stale busy reads reconnecting, an error
// with a code reads its message, a done turn with a BLOCKED result reads
// blocked, anything else is the status word.
function wordView(status, result, code, stale) {
  if (stale && BUSY.indexOf(status) >= 0)
    return { word: string("state.reconnecting"), tone: "muted" }
  if (status === "error" && code)
    return { word: errorMessage(code), tone: "fail" }
  if (status === "done" && /^BLOCKED/.test(result || ""))
    return { word: string("ui.pill.blocked"), tone: "needsYou" }
  return { word: statusWord(status), tone: statusTone(status) }
}

function pillView(status, result) { return wordView(status, result, "", false) }

// Result text -> { text, state, detail }; detail is the raw string when it
// was translated (for a details disclosure), else "".
function translateResult(raw) {
  raw = raw || ""
  for (var i = 0; i < RESULT_RULES.length; i++) {
    var r = RESULT_RULES[i]
    var m = raw.match(new RegExp(r[0]))
    if (m) {
      var text = r[1]
      if (text.indexOf("{1}") >= 0) text = text.replace("{1}", undash(m[1] || ""))
      return { text: text, state: r[2], detail: raw }
    }
  }
  return { text: raw, state: null, detail: "" }
}

function pickLabel(pick) {
  var p = String(pick || "").replace(/^suggestion:/, "")
  var i = p.indexOf(":")
  if (i < 0) return undash(p)
  var kind = p.slice(0, i), val = p.slice(i + 1)
  if (kind === "app") return val === "none" ? "none of these" : val
  if (kind === "action") return ACTION_VERBS[val] || val.replace(/_/g, " ")
  return undash(val)
}
"""


def render() -> str:
    def js(v):
        return json.dumps(v, ensure_ascii=True)
    return "\n".join([
        ".pragma library",
        "",
        "// GENERATED by scripts/assets/gen_copy.py from wisp/copy.py.",
        "// Do not edit; change wisp/copy.py and regenerate.",
        "",
        f"var TONES = {js(list(wcopy.TONES))}",
        f"var STATUS = {js({k: list(v) for k, v in wcopy.STATUS.items()})}",
        f"var UNKNOWN_STATUS = {js(wcopy.UNKNOWN_STATUS)}",
        f"var RESULT_RULES = {js([list(r) for r in wcopy.RESULT_RULES])}",
        f"var ACTION_VERBS = {js(wcopy.ACTION_VERBS)}",
        f"var ERRORS = {js({k: list(v) for k, v in wcopy.ERRORS.items()})}",
        f"var UNKNOWN_ERROR = {js(wcopy.UNKNOWN_ERROR)}",
        f"var STRINGS = {js(wcopy.STRINGS)}",
        f"var BUSY = {js(list(wcopy.BUSY))}",
    ]) + "\n" + _FUNCTIONS


def main(argv) -> int:
    text = render()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run "
                  "python scripts/assets/gen_copy.py")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
